### ISSUE TITLE
client and server don't have same version？How to fix it

### ISSUE THREAD

**Issue by pavlelee** [vukor/docker-web-stack#1]
liv@ubuntu:~$ cd docker/docker-web-stack/
liv@ubuntu:~/docker/docker-web-stack$ docker-compose up -d
client and server don't have same version (client : 1.18, server: 1.14)

**Comment by vukor** [comment]
Try downgrade docker-compose to version 1.2 or upgrade docker.
To install newest stable docker on my ubuntu 14.04 i run this command:
wget -qO- https://get.docker.com/ |sh

**Comment by pavlelee** [comment]
Thank you
